# script variables
export USER_TO_USE=ddps2018
export NAMENODE_HOSTNAME=node059

# setup environment variables
export HDFS_NAMENODE_USER=$USER_TO_USE
export HDFS_DATANODE_USER=$USER_TO_USE
export HDFS_SECONDARYNAMENODE_USER=$USER_TO_USE
export YARN_RESOURCEMANAGER_USER=$USER_TO_USE
export YARN_NODEMANAGER_USER=$USER_TO_USE

export HADOOP_INSTALL=$HADOOP_HOME
export HADOOP_MAPRED_HOME=$HADOOP_HOME
export HADOOP_COMMON_HOME=$HADOOP_HOME
export HADOOP_HDFS_HOME=$HADOOP_HOME
export YARN_HOME=$HADOOP_HOME
# export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
# export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"

export HADOOP_HOME=/home/$USER_TO_USE/ddps_1/hadoop-3.3.0
export HIVE_HOME=/home/$USER_TO_USE/ddps_1/apache-hive-3.1.2-bin

export HADOOP_PATH=$HADOOP_HOME
export HADOOP_YARN_HOME=$HADOOP_HOME