# script variables
export USER_TO_USE=ddps2018
export NAMENODE_HOSTNAME=node063

# setup environment variables
export HDFS_NAMENODE_USER=$USER_TO_USE
export HDFS_DATANODE_USER=$USER_TO_USE
export HDFS_SECONDARYNAMENODE_USER=$USER_TO_USE
export YARN_RESOURCEMANAGER_USER=$USER_TO_USE
export YARN_NODEMANAGER_USER=$USER_TO_USE

export HADOOP_INSTALL=$HADOOP_HOME
export HADOOP_MAPRED_HOME=$HADOOP_HOME
export HADOOP_COMMON_HOME=$HADOOP_HOME
export HADOOP_HDFS_HOME=$HADOOP_HOME
export YARN_HOME=$HADOOP_HOME
# export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
# export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"

export HADOOP_HOME=/local/$USER_TO_USE/hadoop-3.3.0
export HIVE_HOME=/local/$USER_TO_USE/apache-hive-3.1.2-bin
export DERBY_HOME=/local/$USER_TO_USE/db-derby-10.14.1.0-bin

export DERBY_INSTALL=$DERBY_HOME
export CLASSPATH=$DERBY_INSTALL/lib/derbytools.jar:$DERBY_INSTALL/lib/derbynet.jar

export HADOOP_PATH=$HADOOP_HOME
export HADOOP_YARN_HOME=$HADOOP_HOME
export HADOOP=$HADOOP_HOME